# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-13 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Junior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=200)),
                ('link_sns', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=500)),
                ('link_code', models.CharField(max_length=500)),
            ],
        ),
    ]
