# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-13 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='junior',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
    ]
