# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-13 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleform', '0002_junior_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junior',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
