# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-13 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleform', '0003_auto_20180813_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junior',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='junior',
            name='link_code',
            field=models.TextField(),
        ),
    ]
