# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-21 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleform', '0005_junior_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='junior',
            name='english',
            field=models.CharField(default='low', max_length=200),
            preserve_default=False,
        ),
    ]
