# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-22 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littleform', '0006_junior_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='junior',
            name='file',
            field=models.FileField(default=1, upload_to=b'user_files'),
            preserve_default=False,
        ),
    ]
